version: '3'
services:
  hello:
    build: ./hello
    ports:
    - "3000:3000"
  world:
    build: ./world
    ports:
    - "4000:4000"
  nginx:
    build: ./nginx
    ports:
    - "80:80"
    #depends_on:
    #- hello
    #- world
